
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-instructor-report","number":21,"title":"Made Instructor Report Improvements","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-leaderboard-improvements","number":20,"title":"FEATURE: UX improvements to leaderboard page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/pull/20"},{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison","number":19,"title":"Added Lastday","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/pull/19"}]
